# Generated by Django 4.0.4 on 2023-06-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='birtday',
            new_name='birthdate',
        ),
    ]
