# Generated by Django 4.0.4 on 2023-06-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_birtday_client_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_number',
            field=models.IntegerField(default=0, max_length=12, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
    ]
