# Generated by Django 4.0.4 on 2023-06-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_id_number_alter_client_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_number',
            field=models.IntegerField(default=0, verbose_name='Número de documento'),
        ),
    ]
