# Generated by Django 4.0.4 on 2023-06-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_birthdate_alter_client_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_number',
            field=models.BigIntegerField(default=0, verbose_name='Número de documento'),
        ),
    ]
