# Generated by Django 4.0.4 on 2023-06-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_joined',
            field=models.DateField(auto_now_add=True, verbose_name='fecha de registro'),
        ),
    ]
